[project]
name = "rmkernel"
version = "0.1.0"
description = "Remove Kernel in Fedora"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.14.1",
]
